server:
  port: 9003

eureka:
  instance:
    hostname: eureka9003
  client:
    # false表示不向注册中心注册自己。
    registerWithEureka: true
    # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka9000:9000/eureka/,http://eureka9002:9002/eureka/